url: http://wjlroe.github.com
name: William Roe
author: Will
email: willroe@gmail.com
about: "I'm a programmer of various languages living in London"
avatar_link: http://github.com/wjlroe
repos:
  -
    name: arya
    url: https://github.com/wjlroe/arya
  -
    name: lanniser
    url: https://github.com/wjlroe/lannister
  -
    name: parse_perseus
    url: https://github.com/wjlroe/parse_perseus
  -
    name: dotfiles
    url: https://github.com/wjlroe/dotfiles
  -
    name: clj-gae-example
    url: https://github.com/wjlroe/clj-dae-example
  -
    name: smaug
    url: https://github.com/wjlroe/smaug
elsewhere:
  -
    text: Facebook
    href: http://www.facebook.com/wjlroe
  -
    text: Twitter
    href: http://twitter.com/wjlroe
  -
    text: Github
    href: https://github.com/wjlroe
  -
    text: Flickr
    href: http://flickr.com/wjlroe
  -
    text: LinkedIn
    href: http://uk.linkedin.com/in/wjlroe